version: '3'
services:
  database:
    container_name: 'mysql'
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./docker-init:/docker-entrypoint-initdb.d
  cache:
    container_name: 'redis'
    image: redis
    command: redis-server
    restart: always
    ports:
      - 6380:6379
  server:
    container_name: 'express'
    image: 'express'
    build: ./
    restart: always
    ports:
    - 5001:5000
    depends_on:
      - database
      - cache