version: '3'
services:
  database:
    container_name: 'mysql'
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./docker-init:/docker-entrypoint-initdb.d
  cache:
    container_name: 'redis'
    image: redis
    command: redis-server
    restart: always
    ports:
      - 6380:6379
  backend:
    container_name: 'express-backend'
    image: 'express-backend'
    build: .
    restart: always
    ports:
    - 8080:80
    environment:
      MYSQL_PORT: 3307
      REDIS_PORT: 6380
    depends_on:
      - database
      - cache