version: '3'
services:
  mysql:
    container_name: 'mysql'
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./docker-init:/docker-entrypoint-initdb.d
  redis:
    container_name: 'redis'
    image: redis
    command: redis-server
    restart: always
    ports:
      - 6379:6379
  backend:
    container_name: 'backend'
    build: ./
    restart: always
    ports:
    - 80:80
    environment:
      MYSQL_PORT: 3306
      REDIS_PORT: 6379
      REDIS_HOST: redis
      MYSQL_HOST: mysql
      REDIS_ENDPOINT: redis:6379
    depends_on:
      - mysql
      - redis